### ISSUE TITLE
missing DockerfilePassthrough

### ISSUE THREAD

**Issue by redoracle** [leo42/BroClanWallet#80]
<img width="761" alt="image" src="https://github.com/leo42/BroClanWallet/assets/1196958/698fb4ab-96f5-4c9c-ad62-be0c12dcbf4a">

**Comment by leo42** [comment]
Hey, that is a pretty outdated docker-compose. I will update it in the next release, the passthrough service is now an independent codebase https://github.com/leo42/cardanoMultisigSyncService .

In the meanwhile if you tell me the reason you are trying to launch with docker-compose I can offer you an alternative.

**Comment by redoracle** [comment]
Hi, many thanks for your reply. Just testing it, looking around for self hosted mulitsig tools

**Comment by leo42** [comment]
Ahh then I would recommend you just use a single docker instance, you can
find the dockerfile under Fe/Dockerfile.

Or alternativly you can find docker images in dockerhub, name: leo42/broclan
